name: Fastify Application

on:
  push:
    branchs: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2

      - name: Install Fastify Dependencies
        run: ./batect install-dep

      - name: Run testcases
        run: ./batect test-ci
      
      - name: Perform Linting
        run: ./batect lint

  deploy:
    needs: build
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Login to heroku container registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: herouku container:login

      - name: Build docker image and push to heroku registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push -a udemy-learning-fastify-course web

      - name: Run docker imageon heroku
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a udemy-learning-fastify-course web